# Simple Linear Regression

In [55]:
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)  
y = np.array([2, 3, 4, 5, 6])  

model = LinearRegression()
model.fit(X, y)

X_test = np.array([6]).reshape(-1, 1)  
y_pred = model.predict(X_test)
print("Predicted value:", y_pred)

Predicted value: [7.]


# Hours Studies vs Exam Score

In [41]:
import numpy as np
import pandas as pd
np.random.seed(42)
hours_studied = np.random.uniform(1, 10, 100) 
exam_scores = 60 + 5 * hours_studied + np.random.normal(0, 10, 100)  # Exam scores
df = pd.DataFrame({'Hours Studied': hours_studied, 'Exam Scores': exam_scores})
print(df.head())

   Hours Studied  Exam Scores
0       4.370861    82.724776
1       9.556429   104.792070
2       7.587945    98.857335
3       6.387926    72.063943
4       2.404168    69.824120


In [51]:
X = hours_studied
X=X.reshape(-1, 1)
y = exam_scores
regr = linear_model.LinearRegression()
regr.fit(X, y)

LinearRegression()

In [53]:
test_array = np.array([[4.37086107],
                       [9.55642876],
                       [7.58794548],
                       [6.38792636],
                       [2.40416776],
                       [2.4039506]])
predictedCO2 = regr.predict(test_array)
predictedCO2

array([ 82.28323173, 105.56197553,  96.7251768 ,  91.33812194,
        73.45446844,  73.45349358])

# Multiple Linear Regression

In [2]:
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6]])  # Features (independent variables)
y = np.array([3, 5, 7, 9, 11])  # Target (dependent variable)

model = LinearRegression()
model.fit(X, y)

X_test = np.array([[6, 7]])  # New data point to predict
y_pred = model.predict(X_test)
print("Predicted value:", y_pred)

Predicted value: [13.]


# Car Model vs Co2

In [36]:
from sklearn import linear_model
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
df = pd.read_csv(r'C:\Users\HP\Desktop\Nettech\cars.csv')
df.head()

Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [37]:
X = df[['Weight', 'Volume']]
y = df['CO2']
regr = linear_model.LinearRegression()
regr.fit(X, y)
predictedCO2 = regr.predict([[2300, 1300]])

In [38]:
print(predictedCO2)

[107.2087328]


In [39]:
print(regr.coef_)

[0.00755095 0.00780526]


# Logistic Regression

In [11]:
from sklearn.linear_model import LogisticRegression
import numpy as np

X = np.array([[1], [2], [3], [4], [5]])  # Features (independent variable)
y = np.array([0, 0, 1, 1, 1])  # Target (binary classification)

model = LogisticRegression()
model.fit(X, y)

X_test = np.array([[2]]) 
y_pred = model.predict(X_test)
print("Predicted class:", y_pred)

Predicted class: [0]


# Iris Data

In [54]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

iris = load_iris()
X, y = iris.data, iris.target

X = X[:, :2]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.90
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.88      0.78      0.82         9
           2       0.83      0.91      0.87        11

    accuracy                           0.90        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.90      0.90      0.90        30

Confusion Matrix:
[[10  0  0]
 [ 0  7  2]
 [ 0  1 10]]
