In [30]:
import pandas as pd
import numpy as np

In [75]:
data = pd.read_csv(r'C:\Users\HP\Downloads\archive\iphone_purchase_records.csv')
data.head()

Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [77]:
data['Purchase Iphone'].value_counts()

Purchase Iphone
0    257
1    143
Name: count, dtype: int64

In [97]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
newdata  = pd.DataFrame(enc.fit_transform(data[['Gender']]).toarray())
#newdata = pd.DataFrame(newdata,columns=['Female','Male'])
data[['female','male']] = newdata
data.head()

Gender  Age  Salary  Purchase Iphone  female  male
0    Male   19   19000                0     0.0   1.0
1    Male   35   20000                0     0.0   1.0
2  Female   26   43000                0     1.0   0.0
3  Female   27   57000                0     1.0   0.0
4    Male   19   76000                0     0.0   1.0

In [99]:
from sklearn.model_selection import train_test_split

x_new = data.drop(['Purchase Iphone','Gender'],axis=1)
y = data['Purchase Iphone']
xtrain,xtest,ytrain,ytest = train_test_split(x_new,y,test_size=0.25)

In [102]:
from sklearn.linear_model import LogisticRegression
mod1 = LogisticRegression()
mod1.fit(xtrain,ytrain)
preds = mod1.predict(xtest)

In [106]:
mod2 = DecisionTreeClassifier()
mod2.fit(xtrain,ytrain)
preds2 = mod2.predict(xtest)

In [114]:
mod3 = KNeighborsClassifier()
mod3.fit(xtrain,ytrain)
preds3 = mod3.predict(xtest)

In [125]:
from sklearn.ensemble import RandomForestClassifier
mod4 = RandomForestClassifier(n_estimators=1000,min_samples_split=3)
mod4.fit(xtrain,ytrain)
preds4 = mod4.predict(xtest)

In [115]:
confusion_matrix(ytest,preds)  # Logistic Regression 

array([[65,  0],
       [35,  0]], dtype=int64)

In [126]:
confusion_matrix(ytest,preds4)  # Random Forest

array([[57,  8],
       [ 1, 34]], dtype=int64)

In [116]:
confusion_matrix(ytest,preds2)  # Decision Tree

array([[56,  9],
       [ 5, 30]], dtype=int64)

In [117]:
confusion_matrix(ytest,preds3)  # KNN

array([[57,  8],
       [13, 22]], dtype=int64)

In [111]:
accuracy_score(ytest,preds2)  # descision tree

0.86

In [110]:
accuracy_score(ytest,preds)  # Logistic Regression

0.65

In [118]:
accuracy_score(ytest,preds3)  # KNN

0.79

In [127]:
accuracy_score(ytest,preds4)  # Random Forest

0.91

array([[57,  8],
       [13, 22]], dtype=int64)

In [35]:
data = pd.read_csv(r'C:\Users\HP\Downloads\8836201-6f9306ad21398ea43cba4f7d537619d0e07d5ae3\8836201-6f9306ad21398ea43cba4f7d537619d0e07d5ae3\iris.csv')
data.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [48]:
data.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

In [36]:
data.shape

(150, 5)

In [37]:
data.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [46]:
data2 = data.drop('variety',axis=1)
data2.head()
data2.corr()

sepal.length  sepal.width  petal.length  petal.width
sepal.length      1.000000    -0.117570      0.871754     0.817941
sepal.width      -0.117570     1.000000     -0.428440    -0.366126
petal.length      0.871754    -0.428440      1.000000     0.962865
petal.width       0.817941    -0.366126      0.962865     1.000000

In [47]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [33]:
from math import sqrt

def euclidean_distance(a, b):
 return sqrt(sum((e1-e2)**2 for e1, e2 in zip(a,b)))
row1 = [10, 20, 15, 10, 5]
row2 = [12, 24, 18, 8, 7]
dist = euclidean_distance(row1, row2)
print(dist)

6.082762530298219


In [32]:
data['variety'].value_counts()

variety
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

In [70]:
from sklearn.model_selection import train_test_split

x = data.drop('variety',axis=1)
xx = x.drop('petal.length',axis=1)
y = data['variety']
xx

sepal.length  sepal.width  petal.width
0             5.1          3.5          0.2
1             4.9          3.0          0.2
2             4.7          3.2          0.2
3             4.6          3.1          0.2
4             5.0          3.6          0.2
..            ...          ...          ...
145           6.7          3.0          2.3
146           6.3          2.5          1.9
147           6.5          3.0          2.0
148           6.2          3.4          2.3
149           5.9          3.0          1.8

[150 rows x 3 columns]

In [71]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.15)
xxtrain,xxtest,yytrain,yytest = train_test_split(xx,y,test_size=0.15)
print(xxtrain.shape)
print(yytrain.shape)

(127, 3)
(127,)


In [49]:
from sklearn.neighbors import KNeighborsClassifier

In [74]:
model  = KNeighborsClassifier()
model.fit(xtrain,ytrain)

prediction  = model.predict(xtest)
confusion_matrix(ytest,prediction3)
accuracy_score(ytest,prediction3)

0.391304347826087

In [72]:
model3  = KNeighborsClassifier()
model3.fit(xxtrain,yytrain)

prediction3  = model3.predict(xxtest)


In [60]:
from sklearn.metrics import accuracy_score,confusion_matrix 
confusion_matrix(ytest,prediction)

array([[8, 0, 0],
       [0, 6, 1],
       [0, 0, 8]], dtype=int64)

In [61]:
accuracy_score(ytest,prediction)

0.9565217391304348

In [64]:
from sklearn.tree import DecisionTreeClassifier
model2  = DecisionTreeClassifier()
model2.fit(xtrain,ytrain)

prediction2  = model2.predict(xtest)
confusion_matrix(ytest,prediction2)

array([[8, 0, 0],
       [0, 7, 0],
       [0, 0, 8]], dtype=int64)

In [65]:
accuracy_score(ytest,prediction2)

1.0